[project]
name = "blockchain-watcher-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.24.0",
    "alembic>=1.17.2",
    "asyncpg>=0.31.0",
    "psycopg2>=2.9.11",
    "sqlalchemy>=2.0.45",
    "web3>=7.14.0",
    "websockets>=15.0.1",
]
