"""upgrade_transaction_model

Revision ID: 1bf7ccf1939a
Revises: 3787fd600a65
Create Date: 2026-01-05 11:57:51.768677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf7ccf1939a'
down_revision: Union[str, Sequence[str], None] = '3787fd600a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_hash', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('symbol', sa.String(), nullable=False))
    op.create_index(op.f('ix_transactions_tx_hash'), 'transactions', ['tx_hash'], unique=True)
    op.drop_column('transactions', 'symblol')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('symblol', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_transactions_tx_hash'), table_name='transactions')
    op.drop_column('transactions', 'symbol')
    op.drop_column('transactions', 'tx_hash')
    # ### end Alembic commands ###
