"""UserTypeUpgrade

Revision ID: 3787fd600a65
Revises: b2104e28ff66
Create Date: 2026-01-05 11:39:10.689392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3787fd600a65'
down_revision: Union[str, Sequence[str], None] = 'b2104e28ff66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN chat_id TYPE INTEGER USING chat_id::integer')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN chat_id TYPE VARCHAR USING chat_id::varchar')
    # ### end Alembic commands ###
